# Generated by Django 4.0.4 on 2022-06-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSolicitud',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='Id solicitud')),
                ('nombreCompleto', models.CharField(max_length=60, verbose_name='Nombre completo')),
                ('mailSolicitante', models.CharField(max_length=60, verbose_name='Mail del solicitate')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre de usuario')),
                ('mail', models.CharField(max_length=60, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=60, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
