# Generated by Django 4.0.4 on 2022-06-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0002_categoriaplanta_alter_formsolicitud_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoplantas',
            options={'verbose_name_plural': 'NombrePlanta'},
        ),
        migrations.AddField(
            model_name='catalogoplantas',
            name='precioPlanta',
            field=models.IntegerField(default=1, verbose_name='Precio planta'),
            preserve_default=False,
        ),
    ]
