# Generated by Django 4.0.4 on 2022-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0004_alter_catalogoplantas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoplantas',
            name='imagenPlanta',
            field=models.CharField(default=1, max_length=2000, verbose_name='url foto planta'),
            preserve_default=False,
        ),
    ]
