# Generated by Django 4.0.4 on 2022-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0005_catalogoplantas_imagenplanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoplantas',
            name='stockPlanta',
            field=models.IntegerField(default=99, verbose_name='Stock planta'),
            preserve_default=False,
        ),
    ]
