# Generated by Django 4.0.4 on 2022-06-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0006_catalogoplantas_stockplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero boleta')),
                ('precioTotal', models.IntegerField(verbose_name='Precio total')),
                ('fecha', models.DateField(verbose_name='Fecha boleta')),
            ],
        ),
    ]
