# Generated by Django 4.0.4 on 2022-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0007_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('IdCodigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Codigo')),
                ('Porcentaje', models.IntegerField(verbose_name='Porcentaje Descuento')),
            ],
        ),
    ]
