# Generated by Django 4.0.4 on 2022-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0008_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='IdCodigo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Id Codigo'),
        ),
    ]
