# Generated by Django 4.0.4 on 2022-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0009_alter_descuento_idcodigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsolicitud',
            name='suscripcion',
            field=models.BooleanField(default=False, verbose_name='Suscripcion'),
        ),
    ]
