# Generated by Django 4.0.4 on 2022-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0010_formsolicitud_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsolicitud',
            name='suscripcion',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='suscripcion',
            field=models.BooleanField(default=False, verbose_name='Suscripcion'),
        ),
    ]
