# Generated by Django 4.0.4 on 2022-06-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityPlant', '0011_remove_formsolicitud_suscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='suscripcion',
            new_name='Suscripcion',
        ),
    ]
